# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

[integration.mqtt.auth.generic]
servers=["tcp://mosquitto:1883"]
username=""
password=""

# Metrics collection settings.
[metrics]

timezone="Local"

  [metrics.prometheus]
  bind="chirpstack-gateway-bridge:9325"
  endpoint_enabled=true
  APITimingHistogram=true
