version: "3"

services:
  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    volumes:
      - ./configuration/chirpstack-network-server:/etc/chirpstack-network-server

  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3
    ports:
      - 8080:8080
    volumes:
      - ./configuration/chirpstack-application-server:/etc/chirpstack-application-server

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:3
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge

  chirpstack-geolocation-server:
    image: chirpstack/chirpstack-geolocation-server:3
    volumes:
      - ./configuration/chirpstack-geolocation-server:/etc/chirpstack-geolocation-server

  postgresql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    volumes:
      - redisdata:/data

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883

  prometheus:
    image: prom/prometheus:v2.16.0
    ports:
      - 9090:9090
    volumes:
     - ./configuration/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:5.4.3
    ports:
     - 3000:3000
    environment:
      GF_INSTALL_PLUGINS: grafana-simple-json-datasource,jdbranham-diagram-panel
      VIRTUAL_HOST: lnsmonit.MYDOMAIN.ORG
      VIRTUAL_PORT: 3000
      VIRTUAL_PATH: grafana 
    volumes:
    - ./configuration/grafana/grafana.ini:/etc/grafana/grafana.ini
    - ./configuration/grafana/dashboard/:/var/lib/grafana/dashboards/
    - ./configuration/grafana/dashboard.yaml:/etc/grafana/dashboard.yaml
    - ./configuration/grafana/datasources/:/etc/grafana/provisioning/datasources/
    
volumes:
  postgresqldata:
  redisdata:
